name: Android Build
on:
  workflow_dispatch:
    inputs:
      distribution:
        description: Relase Notes
        required: true

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Install NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: android
          cache-read-only: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build APK
        run: npm run build-android-dev

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Android APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: Build Complete
          to: karim@ninjaz.ae
          from: Abanoub Amin
          body: |
            Hello Karim,
            Your build process has been successfully completed. Here are the release notes:
            ${{ inputs.distribution }}

            Best regards,
            Abanoub Amin
